
# /Users/haoxun/Data/Project/GeekCMS/geekcms/parser/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x15n\xda\x8a\xc0g\xdak%\xfd\xf1\x1e\x87E\x05e'
    
_lr_action_items = {'RIGHT_OP':([0,2,3,8,10,11,13,14,15,],[-4,6,-4,17,6,-16,-3,6,-5,]),'DEGREE':([0,2,3,10,11,12,13,14,15,],[-4,8,-4,8,-16,19,-3,8,-5,]),'IDENTIFIER':([0,2,3,4,6,7,9,12,13,14,15,17,18,19,],[-4,11,-4,-10,-14,11,-11,-12,-3,11,-5,-15,11,-13,]),'LEFT_OP':([0,2,3,10,11,13,14,15,],[-4,12,-4,12,-16,-3,12,-5,]),'$end':([0,1,2,3,13,14,15,],[-4,0,-2,-4,-3,-1,-5,]),'NEWLINE':([0,4,5,6,9,10,11,12,16,17,18,19,20,],[3,-10,15,-14,-11,-9,-16,-12,-8,-15,-7,-13,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lines':([0,3,],[2,14,]),'relation':([2,10,14,],[7,18,7,]),'left_rel':([2,10,14,],[4,4,4,]),'right_rel':([2,10,14,],[9,9,9,]),'plugin_name':([2,7,14,18,],[10,16,10,20,]),'start':([0,],[1,]),'line_atom':([2,14,],[13,13,]),'plugin_expr':([2,14,],[5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> NEWLINE lines','start',2,'p_start_newline','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',7),
  ('start -> lines','start',1,'p_start_nonewline','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',12),
  ('lines -> lines line_atom','lines',2,'p_lines_expend','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',17),
  ('lines -> <empty>','lines',0,'p_lines_line_atom','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',22),
  ('line_atom -> plugin_expr NEWLINE','line_atom',2,'p_line_atom','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',27),
  ('plugin_expr -> plugin_name relation plugin_name','plugin_expr',3,'p_plugin_expr_binary','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',32),
  ('plugin_expr -> plugin_name relation','plugin_expr',2,'p_plugin_expr_left','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',37),
  ('plugin_expr -> relation plugin_name','plugin_expr',2,'p_plugin_expr_right','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',42),
  ('plugin_expr -> plugin_name','plugin_expr',1,'p_plugin_expr_none','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',47),
  ('relation -> left_rel','relation',1,'p_relation_left','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',52),
  ('relation -> right_rel','relation',1,'p_relation_right','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',57),
  ('left_rel -> LEFT_OP','left_rel',1,'p_left_rel_nodegree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',62),
  ('left_rel -> LEFT_OP DEGREE','left_rel',2,'p_left_rel_degree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',67),
  ('right_rel -> RIGHT_OP','right_rel',1,'p_right_rel_nodegree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',72),
  ('right_rel -> DEGREE RIGHT_OP','right_rel',2,'p_right_rel_degree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',77),
  ('plugin_name -> IDENTIFIER','plugin_name',1,'p_plugin_name','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',82),
]
