
# /Users/haoxun/Data/Project/GeekCMS/geekcms/parser/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x15n\xda\x8a\xc0g\xdak%\xfd\xf1\x1e\x87E\x05e'
    
_lr_action_items = {'RIGHT_OP':([0,1,3,5,6,10,12,14,17,],[-4,13,-4,-3,16,13,-16,13,-5,]),'$end':([0,1,2,3,5,14,17,],[-4,-2,0,-4,-3,-1,-5,]),'DEGREE':([0,1,3,5,10,11,12,14,17,],[-4,6,-4,-3,6,19,-16,6,-5,]),'NEWLINE':([0,7,8,9,10,11,12,13,15,16,18,19,20,],[3,-11,-10,17,-9,-12,-16,-14,-8,-15,-7,-13,-6,]),'IDENTIFIER':([0,1,3,4,5,7,8,11,13,14,16,17,18,19,],[-4,12,-4,12,-3,-11,-10,-12,-14,12,-15,-5,12,-13,]),'LEFT_OP':([0,1,3,5,10,12,14,17,],[-4,11,-4,-3,11,-16,11,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'relation':([1,10,14,],[4,18,4,]),'left_rel':([1,10,14,],[8,8,8,]),'start':([0,],[2,]),'line_atom':([1,14,],[5,5,]),'plugin_expr':([1,14,],[9,9,]),'lines':([0,3,],[1,14,]),'plugin_name':([1,4,14,18,],[10,15,10,20,]),'right_rel':([1,10,14,],[7,7,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> NEWLINE lines','start',2,'p_start_newline','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',7),
  ('start -> lines','start',1,'p_start_nonewline','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',12),
  ('lines -> lines line_atom','lines',2,'p_lines_expend','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',17),
  ('lines -> <empty>','lines',0,'p_lines_line_atom','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',22),
  ('line_atom -> plugin_expr NEWLINE','line_atom',2,'p_line_atom','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',27),
  ('plugin_expr -> plugin_name relation plugin_name','plugin_expr',3,'p_plugin_expr_binary','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',32),
  ('plugin_expr -> plugin_name relation','plugin_expr',2,'p_plugin_expr_left','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',37),
  ('plugin_expr -> relation plugin_name','plugin_expr',2,'p_plugin_expr_right','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',42),
  ('plugin_expr -> plugin_name','plugin_expr',1,'p_plugin_expr_none','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',47),
  ('relation -> left_rel','relation',1,'p_relation_left','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',52),
  ('relation -> right_rel','relation',1,'p_relation_right','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',57),
  ('left_rel -> LEFT_OP','left_rel',1,'p_left_rel_nodegree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',62),
  ('left_rel -> LEFT_OP DEGREE','left_rel',2,'p_left_rel_degree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',67),
  ('right_rel -> RIGHT_OP','right_rel',1,'p_right_rel_nodegree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',72),
  ('right_rel -> DEGREE RIGHT_OP','right_rel',2,'p_right_rel_degree','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',77),
  ('plugin_name -> IDENTIFIER','plugin_name',1,'p_plugin_name','/Users/haoxun/Data/Project/GeekCMS/geekcms/parser/simple_yacc.py',82),
]
